# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAggregate',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('entity_id', models.UUIDField(default=None, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_data', models.TextField()),
                ('sequence', models.IntegerField()),
                ('entity_id', models.UUIDField()),
            ],
        ),
    ]
