# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('event_data', models.TextField()),
                ('sequence', models.IntegerField()),
                ('guid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
