# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLogAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
