# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expenselogaggregate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselogaggregate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
